version: "3.7"
name: text-processing-project

services:
      rabbitmq:
        image: rabbitmq:management
        ports:
          - "5672:5672"
          - "15672:15672"
      db:
        image: postgres:14.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
